Creating CodeOwners File/Setting Minimul Risk/Placing Task Checks
GetTerminus/convox-off-cluster-builder pull request #30
Opened 2021-12-14 21:24 UTC by xStatick

## Master Status: 
- [ ] Reviewed the Terraform Plan
- [ ] I promise to make sure that master is green before merging into it. 

### Minimal Risk Level:
#### Is this behind a feature toggle?

- [ ] Yes - This is a low risk change
- [ ] No - This is high risk change and must be elevated or higher and you need more approvals

### Description of Changes:

2021-12-15 19:39 UTC, brendanjerwin requested changes

2021-12-15 19:39 UTC, brendanjerwin commented on .github/PULL_REQUEST_TEMPLATE.md
> +## Master Status:
"Master Status"? Weird heading.

2021-12-15 20:25 UTC, xStatick commented on .github/PULL_REQUEST_TEMPLATE.md
> +## Master Status:
header removed

2021-12-16 17:25 UTC, brendanjerwin approved these changes

2022-01-03 21:37 UTC, merged